### ISSUE TITLE
Find deprecated Node.js 12 actions

### ISSUE THREAD

**Issue by joshjohanning** [joshjohanning/github-actions-log-warning-checker#2]
Find warnings similar to:

 
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/stale@v4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by teddyteh** [comment]
Enhanced by #6

**Comment by joshjohanning** [comment]
🎉  complete!
